#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-11-08 16:35:10 +0100
# https://github.com/sshaw/jaxb2ruby
#

require "roxml"

module Libis module Ingester module Teneo
class MetadataDefault

class Search 
  include ROXML

  

  xml_name "Search"



  
      xml_accessor :config, :from => "@config", :required => true
    
  
end

end
end end end
