#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-11-07 11:02:07 +0100
# https://github.com/sshaw/jaxb2ruby
#

require "roxml"

module Libis module Ingester module Teneo
class IngestModel

class Overrides 
  include ROXML

  

  xml_name "Overrides"



  
      xml_accessor :entity_type, :from => "@entity_type", :required => false
    
  
      xml_accessor :user_a, :from => "@user_a", :required => false
    
  
      xml_accessor :user_b, :from => "@user_b", :required => false
    
  
      xml_accessor :user_c, :from => "@user_c", :required => false
    
  
      xml_accessor :status, :from => "@status", :required => false
    
  
end

end
end end end
