#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-10-11 16:35:58 +0200
# https://github.com/sshaw/jaxb2ruby
#

require "roxml"

module Libis module Ingester module Teneo


class Checksum 
  include ROXML

  xml_namespaces "ns1" => "https://teneo.libis.be/schema"

  xml_name "ns1:checksum"


    xml_accessor :content, :from => ".", :required => false

  
      xml_accessor :algorithm, :from => "@algorithm", :required => false
    
  
end


end end end
