#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-10-11 16:35:58 +0200
# https://github.com/sshaw/jaxb2ruby
#

require "roxml"
require "libis/ingester/teneo/ingest_model"

module Libis module Ingester module Teneo


class Config 
  include ROXML

  xml_namespaces "ns1" => "https://teneo.libis.be/schema"

  xml_name "ns1:config"

          xml_accessor :base_dir, :from => "ns1:base_dir", :required => false
          xml_accessor :ingest_model, :as => Libis::Ingester::Teneo::IngestModel, :from => "ns1:ingest_model", :required => false


  
end


end end end
