#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-11-02 00:50:18 +0100
# https://github.com/sshaw/jaxb2ruby
#

require "roxml"

module Libis module Ingester module Teneo


class Config 
  include ROXML

  xml_namespaces "ns1" => "https://teneo.libis.be/schema"

  xml_name "ns1:config"

          xml_accessor :base_dir, :from => "ns1:base_dir", :required => false


  
end


end end end
