#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-11-07 11:02:07 +0100
# https://github.com/sshaw/jaxb2ruby
#

require "roxml"
require "libis/ingester/teneo/checksum"
require "libis/ingester/teneo/file/alt_label"

module Libis module Ingester module Teneo


class File 
  include ROXML

  xml_namespaces "ns1" => "https://teneo.libis.be/schema"

  xml_name "ns1:file"

          xml_accessor :path, :from => "ns1:path", :required => true
          xml_accessor :size, :as => Integer, :from => "ns1:size", :required => false
          xml_accessor :mimetype, :from => "ns1:mimetype", :required => false
    
      xml_accessor :checksas, :as => [Libis::Ingester::Teneo::Checksum], :from => "ns1:checksum", :required => false
    
      xml_accessor :alt_labels, :as => [Libis::Ingester::Teneo::File::AltLabel], :from => "ns1:alt_label", :required => false


  
      xml_accessor :target_rep, :from => "@target_rep", :required => false
    
  
      xml_accessor :id, :from => "@id", :required => true
    
  
      xml_accessor :label, :from => "@label", :required => false
    
  
      xml_accessor :label_template, :from => "@label_template", :required => false
    
  
end


end end end
