#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-11-08 16:35:10 +0100
# https://github.com/sshaw/jaxb2ruby
#

require "roxml"
require "libis/ingester/teneo/file"
require "libis/ingester/teneo/ingest_model"
require "libis/ingester/teneo/metadata"
require "libis/ingester/teneo/pip/option"
require "libis/ingester/teneo/pip/property"

module Libis module Ingester module Teneo


class Ie 
  include ROXML

  xml_namespaces "ns1" => "https://teneo.libis.be/schema/pip"

  xml_name "ns1:ie"

    
      xml_accessor :properties, :as => [Libis::Ingester::Teneo::Pip::Property], :from => "ns1:property", :required => false
    
      xml_accessor :options, :as => [Libis::Ingester::Teneo::Pip::Option], :from => "ns1:option", :required => false
          xml_accessor :metadata, :as => Libis::Ingester::Teneo::Metadata, :from => "ns1:metadata", :required => false
          xml_accessor :ingest_model, :as => Libis::Ingester::Teneo::IngestModel, :from => "ns1:ingest_model", :required => false
          xml_accessor :access_right, :from => "ns1:access_right", :required => false
          xml_accessor :retention_policy, :from => "ns1:retention_policy", :required => false
    
      xml_accessor :files, :as => [Libis::Ingester::Teneo::File], :from => "ns1:file", :required => true


  
      xml_accessor :id, :from => "@id", :required => false
    
  
      xml_accessor :label, :from => "@label", :required => false
    
  
      xml_accessor :label_template, :from => "@label_template", :required => false
    
  
end


end end end
