#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-11-02 00:50:18 +0100
# https://github.com/sshaw/jaxb2ruby
#

require "roxml"

module Libis module Ingester module Teneo


class IeDefault 
  include ROXML

  xml_namespaces "ns1" => "https://teneo.libis.be/schema"

  xml_name "ns1:ie_default"



  
      xml_accessor :ingest_model, :from => "@ingest_model", :required => false
    
  
      xml_accessor :access_right, :from => "@access_right", :required => false
    
  
      xml_accessor :retention_policy, :from => "@retention_policy", :required => false
    
  
end


end end end
