#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-11-08 16:35:10 +0100
# https://github.com/sshaw/jaxb2ruby
#

require "roxml"
require "libis/ingester/teneo/ingest_model"

module Libis module Ingester module Teneo


class IeDefault 
  include ROXML

  xml_namespaces "ns1" => "https://teneo.libis.be/schema/pip"

  xml_name "ns1:ie_default"

          xml_accessor :ingest_model, :as => Libis::Ingester::Teneo::IngestModel, :from => "ns1:ingest_model", :required => false
          xml_accessor :access_right, :from => "ns1:access_right", :required => false
          xml_accessor :retention_policy, :from => "ns1:retention_policy", :required => false


  
end


end end end
