#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-11-07 11:02:07 +0100
# https://github.com/sshaw/jaxb2ruby
#

require "roxml"
require "libis/ingester/teneo/ingest_model/overrides"

module Libis module Ingester module Teneo


class IngestModel 
  include ROXML

  xml_namespaces "ns1" => "https://teneo.libis.be/schema"

  xml_name "ns1:ingest_model"

          xml_accessor :overrides, :as => Libis::Ingester::Teneo::IngestModel::Overrides, :from => "ns1:overrides", :required => false


  
      xml_accessor :name, :from => "@name", :required => true
    
  
end


end end end
