#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-10-31 12:00:29 +0100
# https://github.com/sshaw/jaxb2ruby
#

require "roxml"

module Libis module Ingester module Teneo


class IngestModel 
  include ROXML

  xml_namespaces "ns1" => "https://teneo.libis.be/schema"

  xml_name "ns1:ingest_model"



  
      xml_accessor :name, :from => "@name", :required => true
    
  
end


end end end
