#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-10-11 16:35:58 +0200
# https://github.com/sshaw/jaxb2ruby
#

require "roxml"
require "libis/ingester/teneo/ingest_job/option"

module Libis module Ingester module Teneo


class IngestJob 
  include ROXML

  xml_namespaces "ns1" => "https://teneo.libis.be/schema"

  xml_name "ns1:ingest_job"

    
      xml_accessor :options, :as => [Libis::Ingester::Teneo::IngestJob::Option], :from => "ns1:option", :required => false


  
      xml_accessor :name, :from => "@name", :required => false
    
  
end


end end end
