#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-11-07 11:02:07 +0100
# https://github.com/sshaw/jaxb2ruby
#

require "roxml"
require "libis/ingester/teneo/dc_element"
require "libis/ingester/teneo/metadata_default/file"
require "libis/ingester/teneo/metadata_default/search"

module Libis module Ingester module Teneo


class MetadataDefault 
  include ROXML

  xml_namespaces "ns1" => "https://teneo.libis.be/schema"

  xml_name "ns1:metadata_default"

          xml_accessor :search, :as => Libis::Ingester::Teneo::MetadataDefault::Search, :from => "ns1:search", :required => false
          xml_accessor :file, :as => Libis::Ingester::Teneo::MetadataDefault::File, :from => "ns1:file", :required => false
          xml_accessor :record, :from => "ns1:record", :required => false
    
      xml_accessor :prepends, :as => [Libis::Ingester::Teneo::DcElement], :from => "ns1:prepend", :required => false
    
      xml_accessor :appends, :as => [Libis::Ingester::Teneo::DcElement], :from => "ns1:append", :required => false


  
end


end end end
