#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-11-05 17:13:47 +0100
# https://github.com/sshaw/jaxb2ruby
#

require "roxml"

module Libis module Ingester module Teneo
class File

class AltLabel 
  include ROXML

  

  xml_name "AltLabel"


    xml_accessor :content, :from => ".", :required => false

  
      xml_accessor :separator, :from => "@separator", :required => false
    
  
end

end
end end end
