#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-10-11 16:35:58 +0200
# https://github.com/sshaw/jaxb2ruby
#

require "roxml"

module Libis module Ingester module Teneo
class Metadata

class Search 
  include ROXML

  

  xml_name "Search"



  
      xml_accessor :config, :from => "@config", :required => true
    
  
      xml_accessor :key, :from => "@key", :required => true
    
  
end

end
end end end
